node {
   // variable definition
   def commit_id 
   
   // stage: defines building stages
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id" // put the commit id to file
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') { // jenkins tool name
       sh 'npm install --only=dev' // install only dev dependencies in package.json
       sh 'npm test' // test files
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') { // dockerhub: registry credential on jenkins
       def app = docker.build("enesccinar/docker-demo:${commit_id}", '.').push()
     }
   }
   
//stages might be clean>build>test>publish
}
